### ISSUE TITLE
self.delay for arduino mode

### ISSUE THREAD

**Issue by danieljdenman** [dougollerenshaw/syringe_pump#1]
hi Doug! finally got around to setting this up in the lab.
mostly working in one afternoon. motor isn't stepping but maybe the controller is bad or my power supply the motor is bad. 
one bug, line 62 of stepper.py
`self.delay = 0.00025 # delay between ttl pulses when stepping`
should move one indent up, so that it can be used in both arduino and rpi mode.

**Comment by dougollerenshaw** [comment]
Nice catch. Fixed in commit c6ed76d317a003e49091f6f981f07f83354bde7d
