### ISSUE TITLE
mc1,2,3 with ArduinoMega

### ISSUE THREAD

**Issue by danieljdenman** [dougollerenshaw/syringe_pump#2]
also, i used
`self.arduino = ArduinoMega(port)` 
at line 46, since i apparently bought ArduinoMega (and of course imported ArduinoMega from pyfirmata). 
are the mc1, mc2,and mc3 values in the config likely to be different?

**Comment by danieljdenman** [comment]
specified the pins in `configuration_values` in config.py. working! closed.

**Comment by dougollerenshaw** [comment]
Great! Does this mean that the stepping issue you mentioned in issue #1 is solved? Is it fully working now?

**Comment by dougollerenshaw** [comment]
Just in case, I've noticed that the stepper driver is somewhat fragile. If you make a mistake in wiring, it's easy to burn out an internal component, which makes troubleshooting tough. It's sometimes worth plugging a new driver into your breadboard if you've triple-checked the wiring and the stepper still won't step.

**Comment by danieljdenman** [comment]
yes, working now. i remembered that you had burned a driver out, so i had cycled through a few in troubleshooting! but i don't think the driver was the issue (i made a mistake in the wiring and RESET and SLEEP weren't tied to each other. doing that finally got the driver producing its output).

i haven't calibrated yet so don't know if it *fully* working, but commands to dispense and retract seem to work, and the travel is proportional to the amount. 

in addition to reward delivery, i'm still hoping to print a version that holds a hamilton syringe, to use it for nL - uL injections. will update if i get this done.

**Comment by dougollerenshaw** [comment]
Good news. Let me know how it goes. I'd appreciate PR submissions if you make any useful code changes. The readme is in particular need of help if you have time to add any notes you make during the setup process.
